language: lua

env:
  - LUA=""
  - LUA="luajit"

branches:
  only:
    - master

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted
  - sudo luarocks install luasocket

services:
  - cassandra

script: "busted spec"

notifications:
  webhooks:
    - http://my-url/travis-results
  recipients:
    - jbochi@gmail.com
  email:
    on_success: change
    on_failure: always
